-- ============================================================================
-- Prism Consumer Goods (PCG) - ERP Schema
-- ============================================================================
-- Target: DuckDB
-- Auto-generated by: scripts/erp/schema.py
-- ============================================================================

-- Drop all tables (reverse dependency order) for clean reload
DROP TABLE IF EXISTS trade_deductions;
DROP TABLE IF EXISTS promo_events;
DROP TABLE IF EXISTS trade_programs;
DROP TABLE IF EXISTS ar_receipts;
DROP TABLE IF EXISTS ap_payments;
DROP TABLE IF EXISTS invoice_variances;
DROP TABLE IF EXISTS ar_invoice_lines;
DROP TABLE IF EXISTS ar_invoices;
DROP TABLE IF EXISTS ap_invoice_lines;
DROP TABLE IF EXISTS ap_invoices;
DROP TABLE IF EXISTS gl_journal;
DROP TABLE IF EXISTS chart_of_accounts;
DROP TABLE IF EXISTS disposition_logs;
DROP TABLE IF EXISTS return_lines;
DROP TABLE IF EXISTS returns;
DROP TABLE IF EXISTS demand_forecasts;
DROP TABLE IF EXISTS route_segments;
DROP TABLE IF EXISTS inventory;
DROP TABLE IF EXISTS shipment_lines;
DROP TABLE IF EXISTS shipments;
DROP TABLE IF EXISTS retail_locations;
DROP TABLE IF EXISTS distribution_centers;
DROP TABLE IF EXISTS order_lines;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS channels;
DROP TABLE IF EXISTS skus;
DROP TABLE IF EXISTS bulk_intermediates;
DROP TABLE IF EXISTS batch_ingredients;
DROP TABLE IF EXISTS batches;
DROP TABLE IF EXISTS work_orders;
DROP TABLE IF EXISTS formula_ingredients;
DROP TABLE IF EXISTS formulas;
DROP TABLE IF EXISTS production_lines;
DROP TABLE IF EXISTS plants;
DROP TABLE IF EXISTS goods_receipt_lines;
DROP TABLE IF EXISTS goods_receipts;
DROP TABLE IF EXISTS purchase_order_lines;
DROP TABLE IF EXISTS purchase_orders;
DROP TABLE IF EXISTS supplier_ingredients;
DROP TABLE IF EXISTS ingredients;
DROP TABLE IF EXISTS suppliers;

-- ============================================================================
-- DOMAIN A: SOURCE (Procurement & Inbound)
-- ============================================================================

CREATE TABLE suppliers (
    id INTEGER PRIMARY KEY,
    supplier_code VARCHAR UNIQUE NOT NULL,
    name VARCHAR NOT NULL,
    city VARCHAR,
    country VARCHAR NOT NULL,
    lat DECIMAL(10,6),
    lon DECIMAL(10,6),
    tier INTEGER NOT NULL DEFAULT 1,
    is_active BOOLEAN DEFAULT true
);

CREATE TABLE ingredients (
    id INTEGER PRIMARY KEY,
    ingredient_code VARCHAR UNIQUE NOT NULL,
    name VARCHAR NOT NULL,
    category VARCHAR NOT NULL,
    subcategory VARCHAR,
    bom_level INTEGER DEFAULT 2,
    weight_kg DECIMAL(12,4),
    cost_per_kg DECIMAL(12,4),
    unit_of_measure VARCHAR NOT NULL DEFAULT 'kg',
    is_active BOOLEAN DEFAULT true
);

CREATE TABLE supplier_ingredients (
    id INTEGER PRIMARY KEY,
    supplier_id INTEGER NOT NULL,
    ingredient_id INTEGER NOT NULL,
    unit_cost DECIMAL(12,4) NOT NULL,
    lead_time_days INTEGER NOT NULL,
    min_order_qty DECIMAL(12,2) NOT NULL,
    FOREIGN KEY (supplier_id) REFERENCES suppliers(id),
    FOREIGN KEY (ingredient_id) REFERENCES ingredients(id)
);

CREATE TABLE purchase_orders (
    id INTEGER PRIMARY KEY,
    po_number VARCHAR NOT NULL,
    supplier_id INTEGER,
    plant_id INTEGER,
    order_date INTEGER NOT NULL,
    status VARCHAR DEFAULT 'open',
    transaction_sequence_id BIGINT NOT NULL,
    FOREIGN KEY (supplier_id) REFERENCES suppliers(id)
);

CREATE TABLE purchase_order_lines (
    po_id INTEGER NOT NULL,
    line_number INTEGER NOT NULL,
    ingredient_id INTEGER NOT NULL,
    quantity_kg DECIMAL(12,2) NOT NULL,
    unit_cost DECIMAL(10,4),
    status VARCHAR DEFAULT 'open',
    FOREIGN KEY (po_id) REFERENCES purchase_orders(id),
    PRIMARY KEY (po_id, line_number)
);

CREATE TABLE goods_receipts (
    id INTEGER PRIMARY KEY,
    gr_number VARCHAR UNIQUE NOT NULL,
    shipment_id INTEGER,
    plant_id INTEGER,
    receipt_date INTEGER NOT NULL,
    status VARCHAR DEFAULT 'received',
    transaction_sequence_id BIGINT NOT NULL
);

CREATE TABLE goods_receipt_lines (
    gr_id INTEGER NOT NULL,
    line_number INTEGER NOT NULL,
    ingredient_id INTEGER NOT NULL,
    quantity_kg DECIMAL(12,2) NOT NULL,
    FOREIGN KEY (gr_id) REFERENCES goods_receipts(id),
    PRIMARY KEY (gr_id, line_number)
);

-- ============================================================================
-- DOMAIN B: TRANSFORM (Manufacturing)
-- ============================================================================

CREATE TABLE plants (
    id INTEGER PRIMARY KEY,
    plant_code VARCHAR UNIQUE NOT NULL,
    name VARCHAR NOT NULL,
    city VARCHAR NOT NULL,
    country VARCHAR NOT NULL,
    lat DECIMAL(10,6),
    lon DECIMAL(10,6),
    capacity_tons_per_day DECIMAL(10,2),
    is_active BOOLEAN DEFAULT true
);

CREATE TABLE production_lines (
    id INTEGER PRIMARY KEY,
    line_code VARCHAR UNIQUE NOT NULL,
    name VARCHAR NOT NULL,
    plant_id INTEGER NOT NULL,
    line_type VARCHAR NOT NULL,
    capacity_units_per_hour INTEGER NOT NULL,
    is_active BOOLEAN DEFAULT true,
    FOREIGN KEY (plant_id) REFERENCES plants(id)
);

CREATE TABLE formulas (
    id INTEGER PRIMARY KEY,
    formula_code VARCHAR UNIQUE NOT NULL,
    name VARCHAR NOT NULL,
    product_id INTEGER,
    bom_level INTEGER NOT NULL DEFAULT 0,
    batch_size_kg DECIMAL(10,2) NOT NULL,
    yield_percent DECIMAL(5,2) DEFAULT 98.0,
    run_rate_cases_per_hour DECIMAL(10,2),
    changeover_time_hours DECIMAL(5,2)
);

CREATE TABLE formula_ingredients (
    formula_id INTEGER NOT NULL,
    ingredient_id INTEGER NOT NULL,
    sequence INTEGER NOT NULL,
    quantity_kg DECIMAL(10,6) NOT NULL,
    FOREIGN KEY (formula_id) REFERENCES formulas(id),
    PRIMARY KEY (formula_id, ingredient_id, sequence)
);

CREATE TABLE work_orders (
    id INTEGER PRIMARY KEY,
    wo_number VARCHAR UNIQUE NOT NULL,
    plant_id INTEGER NOT NULL,
    formula_id INTEGER NOT NULL,
    planned_quantity_kg DECIMAL(12,2) NOT NULL,
    planned_start_date INTEGER NOT NULL,
    due_date INTEGER,
    status VARCHAR DEFAULT 'planned',
    transaction_sequence_id BIGINT NOT NULL
);

CREATE TABLE batches (
    id INTEGER PRIMARY KEY,
    batch_number VARCHAR UNIQUE NOT NULL,
    wo_id INTEGER,
    plant_id INTEGER,
    formula_id INTEGER,
    product_id INTEGER,
    quantity_kg DECIMAL(12,2) NOT NULL,
    yield_percent DECIMAL(5,2),
    production_date INTEGER NOT NULL,
    status VARCHAR DEFAULT 'pending',
    product_type VARCHAR,
    bom_level INTEGER DEFAULT 0,
    transaction_sequence_id BIGINT NOT NULL,
    FOREIGN KEY (plant_id) REFERENCES plants(id),
    FOREIGN KEY (formula_id) REFERENCES formulas(id)
);

CREATE TABLE batch_ingredients (
    id INTEGER PRIMARY KEY,
    batch_id INTEGER NOT NULL,
    ingredient_id INTEGER NOT NULL,
    quantity_kg DECIMAL(12,4) NOT NULL,
    FOREIGN KEY (batch_id) REFERENCES batches(id)
);

-- ============================================================================
-- DOMAIN C: PRODUCT (SKU Master)
-- ============================================================================

CREATE TABLE bulk_intermediates (
    id INTEGER PRIMARY KEY,
    bulk_code VARCHAR UNIQUE NOT NULL,
    name VARCHAR NOT NULL,
    category VARCHAR,
    bom_level INTEGER NOT NULL DEFAULT 1,
    weight_kg DECIMAL(12,4),
    cost_per_kg DECIMAL(12,4),
    unit_of_measure VARCHAR DEFAULT 'kg',
    is_active BOOLEAN DEFAULT true
);

CREATE TABLE skus (
    id INTEGER PRIMARY KEY,
    sku_code VARCHAR UNIQUE NOT NULL,
    name VARCHAR NOT NULL,
    category VARCHAR,
    brand VARCHAR,
    units_per_case INTEGER DEFAULT 12,
    weight_kg DECIMAL(10,2),
    cost_per_case DECIMAL(10,2),
    price_per_case DECIMAL(10,2),
    value_segment VARCHAR,
    is_active BOOLEAN DEFAULT true,
    supersedes_sku_id INTEGER
);

-- ============================================================================
-- DOMAIN D: ORDER (Demand Signal)
-- ============================================================================

CREATE TABLE channels (
    id INTEGER PRIMARY KEY,
    channel_code VARCHAR UNIQUE NOT NULL,
    name VARCHAR NOT NULL,
    channel_type VARCHAR NOT NULL,
    is_active BOOLEAN DEFAULT true
);

CREATE TABLE orders (
    id INTEGER PRIMARY KEY,
    order_number VARCHAR UNIQUE NOT NULL,
    day INTEGER NOT NULL,
    source_id INTEGER,
    retail_location_id INTEGER,
    status VARCHAR DEFAULT 'pending',
    total_cases INTEGER,
    transaction_sequence_id BIGINT NOT NULL
);

CREATE TABLE order_lines (
    order_id INTEGER NOT NULL,
    line_number INTEGER NOT NULL,
    sku_id INTEGER NOT NULL,
    quantity_cases DECIMAL(12,2) NOT NULL,
    unit_price DECIMAL(10,2),
    status VARCHAR DEFAULT 'open',
    FOREIGN KEY (order_id) REFERENCES orders(id),
    PRIMARY KEY (order_id, line_number)
);

-- ============================================================================
-- DOMAIN E: FULFILL (Outbound)
-- ============================================================================

CREATE TABLE distribution_centers (
    id INTEGER PRIMARY KEY,
    dc_code VARCHAR UNIQUE NOT NULL,
    name VARCHAR NOT NULL,
    city VARCHAR NOT NULL,
    country VARCHAR NOT NULL,
    lat DECIMAL(10,6),
    lon DECIMAL(10,6),
    type VARCHAR NOT NULL,
    is_active BOOLEAN DEFAULT true
);

CREATE TABLE retail_locations (
    id INTEGER PRIMARY KEY,
    location_code VARCHAR UNIQUE NOT NULL,
    name VARCHAR NOT NULL,
    city VARCHAR NOT NULL,
    country VARCHAR NOT NULL,
    lat DECIMAL(10,6),
    lon DECIMAL(10,6),
    store_format VARCHAR,
    channel VARCHAR,
    is_active BOOLEAN DEFAULT true
);

CREATE TABLE shipments (
    id INTEGER PRIMARY KEY,
    shipment_number VARCHAR UNIQUE NOT NULL,
    ship_date INTEGER NOT NULL,
    arrival_date INTEGER,
    origin_id INTEGER,
    destination_id INTEGER,
    status VARCHAR DEFAULT 'planned',
    route_type VARCHAR,
    freight_cost DECIMAL(12,2),
    total_weight_kg DECIMAL(12,2),
    transaction_sequence_id BIGINT NOT NULL
);

CREATE TABLE shipment_lines (
    shipment_id INTEGER NOT NULL,
    line_number INTEGER NOT NULL,
    sku_id INTEGER NOT NULL,
    quantity_cases DECIMAL(12,2) NOT NULL,
    weight_kg DECIMAL(10,2),
    FOREIGN KEY (shipment_id) REFERENCES shipments(id),
    PRIMARY KEY (shipment_id, line_number)
);

CREATE TABLE inventory (
    id INTEGER PRIMARY KEY,
    day INTEGER NOT NULL,
    location_type VARCHAR,
    location_id INTEGER,
    sku_id INTEGER NOT NULL,
    quantity_cases DECIMAL(12,2) NOT NULL DEFAULT 0
);

-- ============================================================================
-- DOMAIN E2: LOGISTICS (Transport Network)
-- ============================================================================

CREATE TABLE route_segments (
    id INTEGER PRIMARY KEY,
    segment_code VARCHAR UNIQUE NOT NULL,
    origin_type VARCHAR NOT NULL,
    origin_id INTEGER NOT NULL,
    destination_type VARCHAR NOT NULL,
    destination_id INTEGER NOT NULL,
    transport_mode VARCHAR NOT NULL,
    distance_km DECIMAL(10,2),
    transit_time_hours DECIMAL(8,2)
);

-- ============================================================================
-- DOMAIN F: PLAN (Demand & Supply Planning)
-- ============================================================================

CREATE TABLE demand_forecasts (
    id INTEGER PRIMARY KEY,
    forecast_version VARCHAR NOT NULL,
    sku_id INTEGER NOT NULL,
    location_type VARCHAR NOT NULL,
    forecast_date INTEGER NOT NULL,
    forecast_quantity_cases DECIMAL(12,2) NOT NULL,
    forecast_type VARCHAR NOT NULL
);

-- ============================================================================
-- DOMAIN G: RETURN (Regenerate)
-- ============================================================================

CREATE TABLE returns (
    id INTEGER PRIMARY KEY,
    return_number VARCHAR UNIQUE NOT NULL,
    return_date INTEGER NOT NULL,
    source_id INTEGER NOT NULL,
    dc_id INTEGER NOT NULL,
    status VARCHAR DEFAULT 'received',
    transaction_sequence_id BIGINT NOT NULL
);

CREATE TABLE return_lines (
    return_id INTEGER NOT NULL,
    line_number INTEGER NOT NULL,
    sku_id INTEGER NOT NULL,
    quantity_cases DECIMAL(12,2) NOT NULL,
    condition VARCHAR NOT NULL,
    FOREIGN KEY (return_id) REFERENCES returns(id),
    PRIMARY KEY (return_id, line_number)
);

CREATE TABLE disposition_logs (
    return_id INTEGER NOT NULL,
    return_line_number INTEGER NOT NULL,
    disposition VARCHAR NOT NULL,
    quantity_cases DECIMAL(12,2) NOT NULL,
    FOREIGN KEY (return_id) REFERENCES returns(id)
);

-- ============================================================================
-- DOMAIN H: FINANCE
-- ============================================================================

CREATE TABLE chart_of_accounts (
    id INTEGER PRIMARY KEY,
    account_code VARCHAR UNIQUE NOT NULL,
    account_name VARCHAR NOT NULL,
    account_type VARCHAR NOT NULL,
    is_active BOOLEAN DEFAULT true
);

CREATE TABLE gl_journal (
    id INTEGER PRIMARY KEY,
    transaction_sequence_id BIGINT NOT NULL,
    entry_date INTEGER NOT NULL,
    posting_date INTEGER NOT NULL,
    account_code VARCHAR NOT NULL,
    debit_amount DECIMAL(14,4) DEFAULT 0,
    credit_amount DECIMAL(14,4) DEFAULT 0,
    reference_type VARCHAR NOT NULL,
    reference_id VARCHAR,
    node_id VARCHAR,
    product_id VARCHAR,
    description VARCHAR,
    is_reversal BOOLEAN DEFAULT false
);

CREATE TABLE ap_invoices (
    id INTEGER PRIMARY KEY,
    transaction_sequence_id BIGINT NOT NULL,
    invoice_number VARCHAR UNIQUE NOT NULL,
    supplier_id INTEGER,
    gr_id INTEGER,
    invoice_date INTEGER NOT NULL,
    due_date INTEGER NOT NULL,
    total_amount DECIMAL(14,4) NOT NULL,
    currency VARCHAR DEFAULT 'USD',
    status VARCHAR DEFAULT 'open',
    FOREIGN KEY (supplier_id) REFERENCES suppliers(id),
    FOREIGN KEY (gr_id) REFERENCES goods_receipts(id)
);

CREATE TABLE ap_invoice_lines (
    invoice_id INTEGER NOT NULL,
    line_number INTEGER NOT NULL,
    ingredient_id INTEGER NOT NULL,
    quantity_kg DECIMAL(12,4) NOT NULL,
    unit_cost DECIMAL(10,4) NOT NULL,
    line_amount DECIMAL(14,4) NOT NULL,
    FOREIGN KEY (invoice_id) REFERENCES ap_invoices(id),
    PRIMARY KEY (invoice_id, line_number)
);

CREATE TABLE ar_invoices (
    id INTEGER PRIMARY KEY,
    transaction_sequence_id BIGINT NOT NULL,
    invoice_number VARCHAR UNIQUE NOT NULL,
    customer_location_id INTEGER,
    shipment_id INTEGER,
    invoice_date INTEGER NOT NULL,
    due_date INTEGER NOT NULL,
    total_amount DECIMAL(14,4) NOT NULL,
    currency VARCHAR DEFAULT 'USD',
    channel VARCHAR,
    status VARCHAR DEFAULT 'open',
    FOREIGN KEY (shipment_id) REFERENCES shipments(id)
);

CREATE TABLE ar_invoice_lines (
    invoice_id INTEGER NOT NULL,
    line_number INTEGER NOT NULL,
    sku_id INTEGER NOT NULL,
    quantity_cases DECIMAL(12,2) NOT NULL,
    unit_price DECIMAL(10,4) NOT NULL,
    line_amount DECIMAL(14,4) NOT NULL,
    FOREIGN KEY (invoice_id) REFERENCES ar_invoices(id),
    PRIMARY KEY (invoice_id, line_number)
);

-- ============================================================================
-- DOMAIN: TRADE MANAGEMENT
-- ============================================================================

CREATE TABLE trade_programs (
    id INTEGER PRIMARY KEY,
    program_code VARCHAR UNIQUE NOT NULL,
    name VARCHAR NOT NULL,
    channel_id INTEGER NOT NULL,
    program_type VARCHAR NOT NULL,
    rate_pct DECIMAL(8,4) NOT NULL,
    start_day INTEGER NOT NULL,
    end_day INTEGER NOT NULL,
    is_active BOOLEAN DEFAULT true,
    FOREIGN KEY (channel_id) REFERENCES channels(id)
);

CREATE TABLE promo_events (
    id INTEGER PRIMARY KEY,
    event_code VARCHAR UNIQUE NOT NULL,
    name VARCHAR NOT NULL,
    trade_program_id INTEGER NOT NULL,
    promo_type VARCHAR NOT NULL,
    sku_id INTEGER NOT NULL,
    start_day INTEGER NOT NULL,
    end_day INTEGER NOT NULL,
    lift_pct DECIMAL(8,4),
    incremental_spend DECIMAL(14,4),
    status VARCHAR DEFAULT 'planned',
    FOREIGN KEY (trade_program_id) REFERENCES trade_programs(id),
    FOREIGN KEY (sku_id) REFERENCES skus(id)
);

CREATE TABLE trade_deductions (
    id INTEGER PRIMARY KEY,
    trade_program_id INTEGER NOT NULL,
    promo_event_id INTEGER,
    ar_invoice_id INTEGER NOT NULL,
    ar_line_number INTEGER NOT NULL,
    sku_id INTEGER NOT NULL,
    list_price_per_case DECIMAL(10,4) NOT NULL,
    quantity_cases DECIMAL(12,2) NOT NULL,
    deduction_amount DECIMAL(14,4) NOT NULL,
    FOREIGN KEY (trade_program_id) REFERENCES trade_programs(id),
    FOREIGN KEY (promo_event_id) REFERENCES promo_events(id),
    FOREIGN KEY (ar_invoice_id) REFERENCES ar_invoices(id),
    FOREIGN KEY (sku_id) REFERENCES skus(id)
);

-- ============================================================================
-- DOMAIN H2: DATA QUALITY & VARIANCES
-- ============================================================================

CREATE TABLE invoice_variances (
    id INTEGER PRIMARY KEY,
    invoice_id INTEGER NOT NULL,
    line_number INTEGER NOT NULL,
    variance_type VARCHAR NOT NULL,
    expected_value DECIMAL(14,4) NOT NULL,
    actual_value DECIMAL(14,4) NOT NULL,
    variance_amount DECIMAL(14,4) NOT NULL,
    resolution_status VARCHAR DEFAULT 'open',
    FOREIGN KEY (invoice_id) REFERENCES ap_invoices(id)
);

CREATE TABLE ap_payments (
    id INTEGER PRIMARY KEY,
    transaction_sequence_id BIGINT NOT NULL,
    invoice_id INTEGER NOT NULL,
    payment_date INTEGER NOT NULL,
    amount DECIMAL(14,4) NOT NULL,
    discount_amount DECIMAL(14,4) DEFAULT 0,
    net_amount DECIMAL(14,4) NOT NULL,
    payment_method VARCHAR DEFAULT 'EFT',
    status VARCHAR DEFAULT 'completed',
    FOREIGN KEY (invoice_id) REFERENCES ap_invoices(id)
);

CREATE TABLE ar_receipts (
    id INTEGER PRIMARY KEY,
    transaction_sequence_id BIGINT NOT NULL,
    invoice_id INTEGER NOT NULL,
    receipt_date INTEGER NOT NULL,
    amount DECIMAL(14,4) NOT NULL,
    status VARCHAR DEFAULT 'completed',
    FOREIGN KEY (invoice_id) REFERENCES ar_invoices(id)
);

-- ============================================================================
-- Indexes
-- ============================================================================

CREATE INDEX idx_orders_day ON orders(day);
CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_shipments_ship_date ON shipments(ship_date);
CREATE INDEX idx_shipments_route_type ON shipments(route_type);
CREATE INDEX idx_shipments_status ON shipments(status);
CREATE INDEX idx_inventory_day ON inventory(day);
CREATE INDEX idx_inventory_location ON inventory(location_id);
CREATE INDEX idx_batches_production_date ON batches(production_date);
CREATE INDEX idx_batches_status ON batches(status);
CREATE INDEX idx_gl_journal_entry_date ON gl_journal(entry_date);
CREATE INDEX idx_gl_journal_account ON gl_journal(account_code);
CREATE INDEX idx_gl_journal_seq ON gl_journal(transaction_sequence_id);
CREATE INDEX idx_gl_journal_reference ON gl_journal(reference_id);
CREATE INDEX idx_ap_invoices_date ON ap_invoices(invoice_date);
CREATE INDEX idx_ar_invoices_date ON ar_invoices(invoice_date);
CREATE INDEX idx_ar_invoices_channel ON ar_invoices(channel);
CREATE INDEX idx_invoice_variances_invoice ON invoice_variances(invoice_id);
CREATE INDEX idx_ap_payments_invoice ON ap_payments(invoice_id);
CREATE INDEX idx_ap_payments_date ON ap_payments(payment_date);
CREATE INDEX idx_ar_receipts_invoice ON ar_receipts(invoice_id);
CREATE INDEX idx_ar_receipts_date ON ar_receipts(receipt_date);
CREATE INDEX idx_purchase_orders_status ON purchase_orders(status);
CREATE INDEX idx_goods_receipts_status ON goods_receipts(status);
CREATE INDEX idx_work_orders_status ON work_orders(status);
CREATE INDEX idx_returns_status ON returns(status);
CREATE INDEX idx_trade_deductions_invoice ON trade_deductions(ar_invoice_id);
CREATE INDEX idx_trade_deductions_program ON trade_deductions(trade_program_id);
CREATE INDEX idx_trade_deductions_sku ON trade_deductions(sku_id);
CREATE INDEX idx_promo_events_program ON promo_events(trade_program_id);
CREATE INDEX idx_promo_events_sku ON promo_events(sku_id);
CREATE INDEX idx_promo_events_dates ON promo_events(start_day, end_day);
