"""
Material and ingredient constants for FMCG data generation.

Contains raw material definitions:
- INGREDIENTS: 50 typical FMCG ingredients (surfactants, abrasives, humectants,
  flavors, fragrances, actives, thickeners, preservatives, colorants, etc.)

Named entities for testing:
- ING-PALM-001: Palm Oil (single-source SPOF)
- ING-SORB-001: Sorbitol (recall trace testing)
- ING-PEPP-001: Peppermint Oil (seasonal availability)
"""

# FMCG Ingredients (50 typical ingredients)
INGREDIENTS = [
    # Problem ingredients (named entities)
    {
        "code": "ING-PALM-001",
        "name": "Palm Oil",
        "category": "surfactant",
        "cas": "8002-75-3",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 365,
    },
    {
        "code": "ING-SORB-001",
        "name": "Sorbitol",
        "category": "humectant",
        "cas": "50-70-4",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 730,
    },
    {
        "code": "ING-PEPP-001",
        "name": "Peppermint Oil",
        "category": "flavor",
        "cas": "8006-90-4",
        "storage": "refrigerated",
        "hazmat": None,
        "shelf_days": 365,
    },
    # Common surfactants
    {
        "code": "ING-SLES-001",
        "name": "Sodium Laureth Sulfate",
        "category": "surfactant",
        "cas": "9004-82-4",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 730,
    },
    {
        "code": "ING-CAPB-001",
        "name": "Cocamidopropyl Betaine",
        "category": "surfactant",
        "cas": "61789-40-0",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 730,
    },
    {
        "code": "ING-LABS-001",
        "name": "Linear Alkylbenzene Sulfonate",
        "category": "surfactant",
        "cas": "68411-30-3",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 730,
    },
    # Abrasives (toothpaste)
    {
        "code": "ING-SICA-001",
        "name": "Silica (Abrasive)",
        "category": "abrasive",
        "cas": "7631-86-9",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 1095,
    },
    {
        "code": "ING-CALC-001",
        "name": "Calcium Carbonate",
        "category": "abrasive",
        "cas": "471-34-1",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 1095,
    },
    {
        "code": "ING-DICA-001",
        "name": "Dicalcium Phosphate",
        "category": "abrasive",
        "cas": "7757-93-9",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 730,
    },
    # Humectants
    {
        "code": "ING-GLYC-001",
        "name": "Glycerin",
        "category": "humectant",
        "cas": "56-81-5",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 730,
    },
    {
        "code": "ING-PROP-001",
        "name": "Propylene Glycol",
        "category": "humectant",
        "cas": "57-55-6",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 730,
    },
    {
        "code": "ING-XYLI-001",
        "name": "Xylitol",
        "category": "humectant",
        "cas": "87-99-0",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 730,
    },
    # Flavors and fragrances
    {
        "code": "ING-SPEA-001",
        "name": "Spearmint Oil",
        "category": "flavor",
        "cas": "8008-79-5",
        "storage": "refrigerated",
        "hazmat": None,
        "shelf_days": 365,
    },
    {
        "code": "ING-MENT-001",
        "name": "Menthol",
        "category": "flavor",
        "cas": "89-78-1",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 730,
    },
    {
        "code": "ING-CINN-001",
        "name": "Cinnamon Flavor",
        "category": "flavor",
        "cas": "104-55-2",
        "storage": "ambient",
        "hazmat": "flammable",
        "shelf_days": 365,
    },
    {
        "code": "ING-LEMO-001",
        "name": "Lemon Fragrance",
        "category": "fragrance",
        "cas": "8008-56-8",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 365,
    },
    {
        "code": "ING-LAVN-001",
        "name": "Lavender Oil",
        "category": "fragrance",
        "cas": "8000-28-0",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 365,
    },
    {
        "code": "ING-VANI-001",
        "name": "Vanilla Fragrance",
        "category": "fragrance",
        "cas": "121-33-5",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 365,
    },
    # Active ingredients (toothpaste)
    {
        "code": "ING-FLUO-001",
        "name": "Sodium Fluoride",
        "category": "active",
        "cas": "7681-49-4",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 1095,
    },
    {
        "code": "ING-STRN-001",
        "name": "Strontium Chloride",
        "category": "active",
        "cas": "10476-85-4",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 730,
    },
    {
        "code": "ING-TRIC-001",
        "name": "Triclosan",
        "category": "active",
        "cas": "3380-34-5",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 730,
    },
    # Thickeners and binders
    {
        "code": "ING-CMC-001",
        "name": "Carboxymethyl Cellulose",
        "category": "thickener",
        "cas": "9004-32-4",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 730,
    },
    {
        "code": "ING-XANT-001",
        "name": "Xanthan Gum",
        "category": "thickener",
        "cas": "11138-66-2",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 730,
    },
    {
        "code": "ING-CARB-001",
        "name": "Carbomer",
        "category": "thickener",
        "cas": "9003-01-4",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 730,
    },
    # Preservatives
    {
        "code": "ING-SODB-001",
        "name": "Sodium Benzoate",
        "category": "preservative",
        "cas": "532-32-1",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 1095,
    },
    {
        "code": "ING-METH-001",
        "name": "Methylparaben",
        "category": "preservative",
        "cas": "99-76-3",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 1095,
    },
    {
        "code": "ING-PHON-001",
        "name": "Phenoxyethanol",
        "category": "preservative",
        "cas": "122-99-6",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 730,
    },
    # Colorants
    {
        "code": "ING-TIO2-001",
        "name": "Titanium Dioxide",
        "category": "colorant",
        "cas": "13463-67-7",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 1095,
    },
    {
        "code": "ING-FDC1-001",
        "name": "FD&C Blue #1",
        "category": "colorant",
        "cas": "3844-45-9",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 1095,
    },
    {
        "code": "ING-FDC5-001",
        "name": "FD&C Yellow #5",
        "category": "colorant",
        "cas": "1934-21-0",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 1095,
    },
    # pH adjusters
    {
        "code": "ING-CITR-001",
        "name": "Citric Acid",
        "category": "ph_adjuster",
        "cas": "77-92-9",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 730,
    },
    {
        "code": "ING-SODH-001",
        "name": "Sodium Hydroxide",
        "category": "ph_adjuster",
        "cas": "1310-73-2",
        "storage": "ambient",
        "hazmat": "corrosive",
        "shelf_days": 1095,
    },
    # Solvents
    {
        "code": "ING-WATR-001",
        "name": "Purified Water",
        "category": "solvent",
        "cas": "7732-18-5",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 365,
    },
    {
        "code": "ING-ETHA-001",
        "name": "Ethanol",
        "category": "solvent",
        "cas": "64-17-5",
        "storage": "ambient",
        "hazmat": "flammable",
        "shelf_days": 730,
    },
    {
        "code": "ING-ISOP-001",
        "name": "Isopropyl Alcohol",
        "category": "solvent",
        "cas": "67-63-0",
        "storage": "ambient",
        "hazmat": "flammable",
        "shelf_days": 730,
    },
    # Emulsifiers
    {
        "code": "ING-STEA-001",
        "name": "Stearic Acid",
        "category": "emulsifier",
        "cas": "57-11-4",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 730,
    },
    {
        "code": "ING-CETE-001",
        "name": "Cetyl Alcohol",
        "category": "emulsifier",
        "cas": "36653-82-4",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 730,
    },
    {
        "code": "ING-POLY-001",
        "name": "Polysorbate 20",
        "category": "emulsifier",
        "cas": "9005-64-5",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 730,
    },
    # Moisturizers
    {
        "code": "ING-SHEA-001",
        "name": "Shea Butter",
        "category": "moisturizer",
        "cas": "91080-23-8",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 365,
    },
    {
        "code": "ING-ALOE-001",
        "name": "Aloe Vera Extract",
        "category": "moisturizer",
        "cas": "8001-97-6",
        "storage": "refrigerated",
        "hazmat": None,
        "shelf_days": 365,
    },
    {
        "code": "ING-COCO-001",
        "name": "Coconut Oil",
        "category": "moisturizer",
        "cas": "8001-31-8",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 365,
    },
    {
        "code": "ING-JOJO-001",
        "name": "Jojoba Oil",
        "category": "moisturizer",
        "cas": "61789-91-1",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 365,
    },
    # Specialty
    {
        "code": "ING-VITA-001",
        "name": "Vitamin E (Tocopherol)",
        "category": "antioxidant",
        "cas": "59-02-9",
        "storage": "refrigerated",
        "hazmat": None,
        "shelf_days": 365,
    },
    {
        "code": "ING-VITC-001",
        "name": "Vitamin C (Ascorbic Acid)",
        "category": "antioxidant",
        "cas": "50-81-7",
        "storage": "refrigerated",
        "hazmat": None,
        "shelf_days": 365,
    },
    {
        "code": "ING-TEA-001",
        "name": "Tea Tree Oil",
        "category": "antibacterial",
        "cas": "68647-73-4",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 365,
    },
    {
        "code": "ING-EUCA-001",
        "name": "Eucalyptus Oil",
        "category": "antibacterial",
        "cas": "8000-48-4",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 365,
    },
    {
        "code": "ING-ZINC-001",
        "name": "Zinc Oxide",
        "category": "active",
        "cas": "1314-13-2",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 1095,
    },
    {
        "code": "ING-SALT-001",
        "name": "Sodium Chloride",
        "category": "viscosity_modifier",
        "cas": "7647-14-5",
        "storage": "ambient",
        "hazmat": None,
        "shelf_days": 1095,
    },
    {
        "code": "ING-ENZY-001",
        "name": "Enzyme Blend",
        "category": "active",
        "cas": None,
        "storage": "refrigerated",
        "hazmat": None,
        "shelf_days": 180,
    },
]
