"""
Network infrastructure constants for FMCG data generation.

Contains logistics and distribution network definitions:
- DCS: 25 distribution centers across 5 divisions
- PORTS: 20 ports (ocean, rail, air hubs)
- CARRIERS: 20 carriers (trucking, LTL, rail, ocean, parcel, 3PL)
"""

# Hardcoded DCs (25 distribution centers)
DCS = [
    # NAM (8 DCs)
    {
        "code": "DC-NAM-CHI-001",
        "name": "Chicago Hub",
        "division": "NAM",
        "country": "USA",
        "city": "Chicago",
        "dc_type": "national",
        "capacity_cases": 2_000_000,
        "lat": 41.8781,
        "lon": -87.6298,
    },
    {
        "code": "DC-NAM-ATL-001",
        "name": "Atlanta DC",
        "division": "NAM",
        "country": "USA",
        "city": "Atlanta",
        "dc_type": "regional",
        "capacity_cases": 800_000,
        "lat": 33.7490,
        "lon": -84.3880,
    },
    {
        "code": "DC-NAM-DAL-001",
        "name": "Dallas DC",
        "division": "NAM",
        "country": "USA",
        "city": "Dallas",
        "dc_type": "regional",
        "capacity_cases": 700_000,
        "lat": 32.7767,
        "lon": -96.7970,
    },
    {
        "code": "DC-NAM-LAX-001",
        "name": "Los Angeles DC",
        "division": "NAM",
        "country": "USA",
        "city": "Los Angeles",
        "dc_type": "regional",
        "capacity_cases": 900_000,
        "lat": 34.0522,
        "lon": -118.2437,
    },
    {
        "code": "DC-NAM-SEA-001",
        "name": "Seattle DC",
        "division": "NAM",
        "country": "USA",
        "city": "Seattle",
        "dc_type": "regional",
        "capacity_cases": 400_000,
        "lat": 47.6062,
        "lon": -122.3321,
    },
    {
        "code": "DC-NAM-NYC-001",
        "name": "New York Metro DC",
        "division": "NAM",
        "country": "USA",
        "city": "Newark",
        "dc_type": "regional",
        "capacity_cases": 600_000,
        "lat": 40.7357,
        "lon": -74.1724,
    },
    {
        "code": "DC-NAM-TOR-001",
        "name": "Toronto DC",
        "division": "NAM",
        "country": "Canada",
        "city": "Toronto",
        "dc_type": "regional",
        "capacity_cases": 500_000,
        "lat": 43.6532,
        "lon": -79.3832,
    },
    {
        "code": "DC-NAM-ECM-001",
        "name": "E-commerce Fulfillment",
        "division": "NAM",
        "country": "USA",
        "city": "Indianapolis",
        "dc_type": "ecommerce",
        "capacity_cases": 300_000,
        "lat": 39.7684,
        "lon": -86.1581,
    },
    # LATAM (4 DCs)
    {
        "code": "DC-LATAM-SP-001",
        "name": "São Paulo DC",
        "division": "LATAM",
        "country": "Brazil",
        "city": "São Paulo",
        "dc_type": "national",
        "capacity_cases": 600_000,
        "lat": -23.5505,
        "lon": -46.6333,
    },
    {
        "code": "DC-LATAM-MEX-001",
        "name": "Mexico City DC",
        "division": "LATAM",
        "country": "Mexico",
        "city": "Mexico City",
        "dc_type": "regional",
        "capacity_cases": 400_000,
        "lat": 19.4326,
        "lon": -99.1332,
    },
    {
        "code": "DC-LATAM-BA-001",
        "name": "Buenos Aires DC",
        "division": "LATAM",
        "country": "Argentina",
        "city": "Buenos Aires",
        "dc_type": "regional",
        "capacity_cases": 250_000,
        "lat": -34.6037,
        "lon": -58.3816,
    },
    {
        "code": "DC-LATAM-LIM-001",
        "name": "Lima DC",
        "division": "LATAM",
        "country": "Peru",
        "city": "Lima",
        "dc_type": "cross_dock",
        "capacity_cases": 150_000,
        "lat": -12.0464,
        "lon": -77.0428,
    },
    # APAC (6 DCs)
    {
        "code": "DC-APAC-SHA-001",
        "name": "Shanghai DC",
        "division": "APAC",
        "country": "China",
        "city": "Shanghai",
        "dc_type": "national",
        "capacity_cases": 800_000,
        "lat": 31.2304,
        "lon": 121.4737,
    },
    {
        "code": "DC-APAC-GZ-001",
        "name": "Guangzhou DC",
        "division": "APAC",
        "country": "China",
        "city": "Guangzhou",
        "dc_type": "regional",
        "capacity_cases": 500_000,
        "lat": 23.1291,
        "lon": 113.2644,
    },
    {
        "code": "DC-APAC-MUM-001",
        "name": "Mumbai DC",
        "division": "APAC",
        "country": "India",
        "city": "Mumbai",
        "dc_type": "national",
        "capacity_cases": 400_000,
        "lat": 19.0760,
        "lon": 72.8777,
    },
    {
        "code": "DC-APAC-SIN-001",
        "name": "Singapore Hub",
        "division": "APAC",
        "country": "Singapore",
        "city": "Singapore",
        "dc_type": "regional",
        "capacity_cases": 350_000,
        "lat": 1.3521,
        "lon": 103.8198,
    },
    {
        "code": "DC-APAC-SYD-001",
        "name": "Sydney DC",
        "division": "APAC",
        "country": "Australia",
        "city": "Sydney",
        "dc_type": "regional",
        "capacity_cases": 250_000,
        "lat": -33.8688,
        "lon": 151.2093,
    },
    {
        "code": "DC-APAC-TYO-001",
        "name": "Tokyo DC",
        "division": "APAC",
        "country": "Japan",
        "city": "Tokyo",
        "dc_type": "regional",
        "capacity_cases": 300_000,
        "lat": 35.6762,
        "lon": 139.6503,
    },
    # EUR (4 DCs)
    {
        "code": "DC-EUR-AMS-001",
        "name": "Amsterdam Hub",
        "division": "EUR",
        "country": "Netherlands",
        "city": "Amsterdam",
        "dc_type": "national",
        "capacity_cases": 500_000,
        "lat": 52.3676,
        "lon": 4.9041,
    },
    {
        "code": "DC-EUR-LON-001",
        "name": "London DC",
        "division": "EUR",
        "country": "UK",
        "city": "London",
        "dc_type": "regional",
        "capacity_cases": 350_000,
        "lat": 51.5074,
        "lon": -0.1278,
    },
    {
        "code": "DC-EUR-PAR-001",
        "name": "Paris DC",
        "division": "EUR",
        "country": "France",
        "city": "Paris",
        "dc_type": "regional",
        "capacity_cases": 300_000,
        "lat": 48.8566,
        "lon": 2.3522,
    },
    {
        "code": "DC-EUR-WAR-001",
        "name": "Warsaw DC",
        "division": "EUR",
        "country": "Poland",
        "city": "Warsaw",
        "dc_type": "cross_dock",
        "capacity_cases": 200_000,
        "lat": 52.2297,
        "lon": 21.0122,
    },
    # AFR-EUR (3 DCs)
    {
        "code": "DC-AFR-DXB-001",
        "name": "Dubai Hub",
        "division": "AFR-EUR",
        "country": "UAE",
        "city": "Dubai",
        "dc_type": "national",
        "capacity_cases": 400_000,
        "lat": 25.2048,
        "lon": 55.2708,
    },
    {
        "code": "DC-AFR-JNB-001",
        "name": "Johannesburg DC",
        "division": "AFR-EUR",
        "country": "South Africa",
        "city": "Johannesburg",
        "dc_type": "regional",
        "capacity_cases": 250_000,
        "lat": -26.2041,
        "lon": 28.0473,
    },
    {
        "code": "DC-AFR-CAI-001",
        "name": "Cairo DC",
        "division": "AFR-EUR",
        "country": "Egypt",
        "city": "Cairo",
        "dc_type": "regional",
        "capacity_cases": 200_000,
        "lat": 30.0444,
        "lon": 31.2357,
    },
]

# Key ports for logistics
PORTS = [
    {
        "code": "USCHI",
        "name": "Chicago Intermodal",
        "port_type": "rail",
        "country": "USA",
        "city": "Chicago",
        "lat": 41.8781,
        "lon": -87.6298,
    },
    {
        "code": "USLAX",
        "name": "Los Angeles",
        "port_type": "ocean",
        "country": "USA",
        "city": "Los Angeles",
        "lat": 33.7405,
        "lon": -118.2609,
    },
    {
        "code": "USNYC",
        "name": "New York/New Jersey",
        "port_type": "ocean",
        "country": "USA",
        "city": "Newark",
        "lat": 40.6688,
        "lon": -74.1490,
    },
    {
        "code": "BRSSZ",
        "name": "Santos",
        "port_type": "ocean",
        "country": "Brazil",
        "city": "Santos",
        "lat": -23.9609,
        "lon": -46.3337,
    },
    {
        "code": "CNSHA",
        "name": "Shanghai",
        "port_type": "ocean",
        "country": "China",
        "city": "Shanghai",
        "lat": 31.2304,
        "lon": 121.4737,
    },
    {
        "code": "CNGUZ",
        "name": "Guangzhou/Nansha",
        "port_type": "ocean",
        "country": "China",
        "city": "Guangzhou",
        "lat": 22.7531,
        "lon": 113.6087,
    },
    {
        "code": "INNSA",
        "name": "Nhava Sheva",
        "port_type": "ocean",
        "country": "India",
        "city": "Mumbai",
        "lat": 18.9491,
        "lon": 72.9426,
    },
    {
        "code": "SGSIN",
        "name": "Singapore",
        "port_type": "ocean",
        "country": "Singapore",
        "city": "Singapore",
        "lat": 1.2650,
        "lon": 103.8200,
    },
    {
        "code": "NLRTM",
        "name": "Rotterdam",
        "port_type": "ocean",
        "country": "Netherlands",
        "city": "Rotterdam",
        "lat": 51.9489,
        "lon": 4.1431,
    },
    {
        "code": "DEHAM",
        "name": "Hamburg",
        "port_type": "ocean",
        "country": "Germany",
        "city": "Hamburg",
        "lat": 53.5461,
        "lon": 9.9660,
    },
    {
        "code": "GBFXT",
        "name": "Felixstowe",
        "port_type": "ocean",
        "country": "UK",
        "city": "Felixstowe",
        "lat": 51.9613,
        "lon": 1.3280,
    },
    {
        "code": "TRIST",
        "name": "Istanbul",
        "port_type": "ocean",
        "country": "Turkey",
        "city": "Istanbul",
        "lat": 41.0020,
        "lon": 28.9870,
    },
    {
        "code": "AEDXB",
        "name": "Jebel Ali",
        "port_type": "ocean",
        "country": "UAE",
        "city": "Dubai",
        "lat": 25.0055,
        "lon": 55.0572,
    },
    {
        "code": "JPYOK",
        "name": "Yokohama",
        "port_type": "ocean",
        "country": "Japan",
        "city": "Yokohama",
        "lat": 35.4521,
        "lon": 139.6381,
    },
    {
        "code": "AUSYD",
        "name": "Sydney",
        "port_type": "ocean",
        "country": "Australia",
        "city": "Sydney",
        "lat": -33.8675,
        "lon": 151.2004,
    },
    {
        "code": "MXVER",
        "name": "Veracruz",
        "port_type": "ocean",
        "country": "Mexico",
        "city": "Veracruz",
        "lat": 19.1738,
        "lon": -96.1342,
    },
    {
        "code": "ARBUE",
        "name": "Buenos Aires",
        "port_type": "ocean",
        "country": "Argentina",
        "city": "Buenos Aires",
        "lat": -34.5771,
        "lon": -58.3728,
    },
    {
        "code": "ZADUR",
        "name": "Durban",
        "port_type": "ocean",
        "country": "South Africa",
        "city": "Durban",
        "lat": -29.8679,
        "lon": 31.0496,
    },
    # Air hubs
    {
        "code": "USORD",
        "name": "Chicago O'Hare",
        "port_type": "air",
        "country": "USA",
        "city": "Chicago",
        "lat": 41.9742,
        "lon": -87.9073,
    },
    {
        "code": "CNSHS",
        "name": "Shanghai Pudong",
        "port_type": "air",
        "country": "China",
        "city": "Shanghai",
        "lat": 31.1434,
        "lon": 121.8052,
    },
]

# Carriers
CARRIERS = [
    # Trucking
    {
        "code": "CAR-TRUK-001",
        "name": "Swift Transport",
        "carrier_type": "trucking",
        "scac": "SWFT",
        "country": "USA",
        "sustainability": "B",
        "otd": 0.94,
    },
    {
        "code": "CAR-TRUK-002",
        "name": "JB Hunt",
        "carrier_type": "trucking",
        "scac": "JBHU",
        "country": "USA",
        "sustainability": "B",
        "otd": 0.95,
    },
    {
        "code": "CAR-TRUK-003",
        "name": "Schneider",
        "carrier_type": "trucking",
        "scac": "SNLU",
        "country": "USA",
        "sustainability": "A",
        "otd": 0.96,
    },
    {
        "code": "CAR-TRUK-004",
        "name": "Werner",
        "carrier_type": "trucking",
        "scac": "WERN",
        "country": "USA",
        "sustainability": "B",
        "otd": 0.93,
    },
    # LTL
    {
        "code": "CAR-LTL-001",
        "name": "Old Dominion",
        "carrier_type": "ltl",
        "scac": "ODFL",
        "country": "USA",
        "sustainability": "B",
        "otd": 0.97,
    },
    {
        "code": "CAR-LTL-002",
        "name": "Estes Express",
        "carrier_type": "ltl",
        "scac": "EXLA",
        "country": "USA",
        "sustainability": "C",
        "otd": 0.92,
    },
    # Rail
    {
        "code": "CAR-RAIL-001",
        "name": "Union Pacific",
        "carrier_type": "rail",
        "scac": "UP",
        "country": "USA",
        "sustainability": "A",
        "otd": 0.88,
    },
    {
        "code": "CAR-RAIL-002",
        "name": "BNSF Railway",
        "carrier_type": "rail",
        "scac": "BNSF",
        "country": "USA",
        "sustainability": "A",
        "otd": 0.90,
    },
    {
        "code": "CAR-RAIL-003",
        "name": "CSX",
        "carrier_type": "rail",
        "scac": "CSXT",
        "country": "USA",
        "sustainability": "A",
        "otd": 0.87,
    },
    # Ocean
    {
        "code": "CAR-OCEAN-001",
        "name": "Maersk Line",
        "carrier_type": "ocean",
        "scac": "MAEU",
        "country": "Denmark",
        "sustainability": "A",
        "otd": 0.85,
    },
    {
        "code": "CAR-OCEAN-002",
        "name": "MSC",
        "carrier_type": "ocean",
        "scac": "MSCU",
        "country": "Switzerland",
        "sustainability": "B",
        "otd": 0.83,
    },
    {
        "code": "CAR-OCEAN-003",
        "name": "CMA CGM",
        "carrier_type": "ocean",
        "scac": "CMDU",
        "country": "France",
        "sustainability": "B",
        "otd": 0.84,
    },
    {
        "code": "CAR-OCEAN-004",
        "name": "Hapag-Lloyd",
        "carrier_type": "ocean",
        "scac": "HLCU",
        "country": "Germany",
        "sustainability": "A",
        "otd": 0.86,
    },
    {
        "code": "CAR-OCEAN-005",
        "name": "COSCO",
        "carrier_type": "ocean",
        "scac": "COSU",
        "country": "China",
        "sustainability": "C",
        "otd": 0.82,
    },
    # Parcel
    {
        "code": "CAR-PARC-001",
        "name": "FedEx",
        "carrier_type": "parcel",
        "scac": "FXFE",
        "country": "USA",
        "sustainability": "A",
        "otd": 0.97,
    },
    {
        "code": "CAR-PARC-002",
        "name": "UPS",
        "carrier_type": "parcel",
        "scac": "UPSS",
        "country": "USA",
        "sustainability": "A",
        "otd": 0.96,
    },
    {
        "code": "CAR-PARC-003",
        "name": "DHL",
        "carrier_type": "parcel",
        "scac": "DHLX",
        "country": "Germany",
        "sustainability": "A",
        "otd": 0.95,
    },
    # 3PL
    {
        "code": "CAR-3PL-001",
        "name": "XPO Logistics",
        "carrier_type": "3pl",
        "scac": "XPOL",
        "country": "USA",
        "sustainability": "B",
        "otd": 0.93,
    },
    {
        "code": "CAR-3PL-002",
        "name": "DHL Supply Chain",
        "carrier_type": "3pl",
        "scac": "DHSC",
        "country": "Germany",
        "sustainability": "A",
        "otd": 0.94,
    },
    {
        "code": "CAR-3PL-003",
        "name": "Kuehne+Nagel",
        "carrier_type": "3pl",
        "scac": "KNIG",
        "country": "Switzerland",
        "sustainability": "A",
        "otd": 0.95,
    },
]
