"""
Business rules and KPI thresholds for FMCG data generation.

Contains operational parameters:
- KPI_THRESHOLDS: 20 KPIs following Desmet Triangle (Service, Cost, Cash)
- BUSINESS_RULES: 14 operational rules (allocation, fulfillment, inventory, etc.)
"""

# KPI Thresholds (Desmet Triangle)
KPI_THRESHOLDS = [
    # Service KPIs
    {
        "code": "KPI-OTIF",
        "name": "On-Time In-Full",
        "category": "service",
        "desmet": "service",
        "unit": "percent",
        "direction": "higher",
        "target": 97.0,
        "warning": 95.0,
        "critical": 93.0,
    },
    {
        "code": "KPI-CFR",
        "name": "Case Fill Rate",
        "category": "service",
        "desmet": "service",
        "unit": "percent",
        "direction": "higher",
        "target": 98.5,
        "warning": 97.0,
        "critical": 95.0,
    },
    {
        "code": "KPI-OSA",
        "name": "On-Shelf Availability",
        "category": "service",
        "desmet": "service",
        "unit": "percent",
        "direction": "higher",
        "target": 95.0,
        "warning": 93.0,
        "critical": 90.0,
    },
    {
        "code": "KPI-POF",
        "name": "Perfect Order Fulfillment",
        "category": "service",
        "desmet": "service",
        "unit": "percent",
        "direction": "higher",
        "target": 92.0,
        "warning": 88.0,
        "critical": 85.0,
    },
    {
        "code": "KPI-FCST",
        "name": "Forecast Accuracy (MAPE)",
        "category": "service",
        "desmet": "service",
        "unit": "percent",
        "direction": "lower",
        "target": 25.0,
        "warning": 30.0,
        "critical": 35.0,
    },
    # Cost KPIs
    {
        "code": "KPI-COGS",
        "name": "COGS % of Revenue",
        "category": "cost",
        "desmet": "cost",
        "unit": "percent",
        "direction": "lower",
        "target": 45.0,
        "warning": 48.0,
        "critical": 52.0,
    },
    {
        "code": "KPI-LCPC",
        "name": "Landed Cost per Case",
        "category": "cost",
        "desmet": "cost",
        "unit": "USD",
        "direction": "lower",
        "target": 8.50,
        "warning": 9.50,
        "critical": 11.00,
    },
    {
        "code": "KPI-FRT",
        "name": "Freight % of Revenue",
        "category": "cost",
        "desmet": "cost",
        "unit": "percent",
        "direction": "lower",
        "target": 6.0,
        "warning": 7.5,
        "critical": 9.0,
    },
    {
        "code": "KPI-WHS",
        "name": "Warehousing Cost per Case",
        "category": "cost",
        "desmet": "cost",
        "unit": "USD",
        "direction": "lower",
        "target": 0.85,
        "warning": 1.00,
        "critical": 1.25,
    },
    {
        "code": "KPI-SCRAP",
        "name": "Scrap Rate",
        "category": "cost",
        "desmet": "cost",
        "unit": "percent",
        "direction": "lower",
        "target": 1.0,
        "warning": 2.0,
        "critical": 3.0,
    },
    # Cash KPIs
    {
        "code": "KPI-INV",
        "name": "Inventory Turns",
        "category": "cash",
        "desmet": "cash",
        "unit": "turns",
        "direction": "higher",
        "target": 10.0,
        "warning": 8.0,
        "critical": 6.0,
    },
    {
        "code": "KPI-DOS",
        "name": "Days of Supply",
        "category": "cash",
        "desmet": "cash",
        "unit": "days",
        "direction": "lower",
        "target": 35.0,
        "warning": 45.0,
        "critical": 60.0,
    },
    {
        "code": "KPI-DSO",
        "name": "Days Sales Outstanding",
        "category": "cash",
        "desmet": "cash",
        "unit": "days",
        "direction": "lower",
        "target": 30.0,
        "warning": 40.0,
        "critical": 50.0,
    },
    {
        "code": "KPI-OBSOL",
        "name": "Obsolete Inventory %",
        "category": "cash",
        "desmet": "cash",
        "unit": "percent",
        "direction": "lower",
        "target": 0.5,
        "warning": 1.0,
        "critical": 2.0,
    },
    {
        "code": "KPI-CCC",
        "name": "Cash Conversion Cycle",
        "category": "cash",
        "desmet": "cash",
        "unit": "days",
        "direction": "lower",
        "target": 45.0,
        "warning": 60.0,
        "critical": 75.0,
    },
    # Quality KPIs
    {
        "code": "KPI-QUAL",
        "name": "First Pass Quality",
        "category": "quality",
        "desmet": None,
        "unit": "percent",
        "direction": "higher",
        "target": 99.0,
        "warning": 98.0,
        "critical": 96.0,
    },
    {
        "code": "KPI-RET",
        "name": "Customer Return Rate",
        "category": "quality",
        "desmet": None,
        "unit": "percent",
        "direction": "lower",
        "target": 0.5,
        "warning": 1.0,
        "critical": 2.0,
    },
    {
        "code": "KPI-COMPL",
        "name": "Customer Complaints per Million",
        "category": "quality",
        "desmet": None,
        "unit": "count",
        "direction": "lower",
        "target": 5.0,
        "warning": 10.0,
        "critical": 20.0,
    },
    # Sustainability KPIs
    {
        "code": "KPI-CO2",
        "name": "CO2 per Case (Scope 3)",
        "category": "sustainability",
        "desmet": None,
        "unit": "kg_co2",
        "direction": "lower",
        "target": 0.25,
        "warning": 0.35,
        "critical": 0.50,
    },
    {
        "code": "KPI-RECYCLE",
        "name": "Packaging Recyclability",
        "category": "sustainability",
        "desmet": None,
        "unit": "percent",
        "direction": "higher",
        "target": 80.0,
        "warning": 65.0,
        "critical": 50.0,
    },
]

# Business Rules
BUSINESS_RULES = [
    {
        "code": "BR-ALLOC-001",
        "name": "Strategic Account Priority",
        "category": "allocation",
        "rule_type": "priority",
        "priority": 10,
        "condition": "account.is_strategic = true",
        "action": "allocate_first",
    },
    {
        "code": "BR-ALLOC-002",
        "name": "FIFO Inventory Allocation",
        "category": "allocation",
        "rule_type": "constraint",
        "priority": 20,
        "condition": "inventory.batch_date",
        "action": "allocate_oldest_first",
    },
    {
        "code": "BR-ALLOC-003",
        "name": "Promotional Demand Reserve",
        "category": "allocation",
        "rule_type": "constraint",
        "priority": 15,
        "condition": "promotion.is_active = true",
        "action": "reserve_promo_qty",
    },
    {
        "code": "BR-FULFILL-001",
        "name": "Minimum Order Quantity",
        "category": "fulfillment",
        "rule_type": "threshold",
        "priority": 50,
        "condition": "order.qty < 10",
        "action": "reject_order",
    },
    {
        "code": "BR-FULFILL-002",
        "name": "Ship Complete Only",
        "category": "fulfillment",
        "rule_type": "constraint",
        "priority": 30,
        "condition": "order.ship_complete = true",
        "action": "hold_partial",
    },
    {
        "code": "BR-FULFILL-003",
        "name": "Direct Ship Threshold",
        "category": "fulfillment",
        "rule_type": "threshold",
        "priority": 40,
        "condition": "order.qty > 1000",
        "action": "direct_ship_eligible",
    },
    {
        "code": "BR-INV-001",
        "name": "Safety Stock Days",
        "category": "inventory",
        "rule_type": "calculation",
        "priority": 25,
        "condition": "always",
        "action": "ss_days = 14",
    },
    {
        "code": "BR-INV-002",
        "name": "Shelf Life Minimum",
        "category": "inventory",
        "rule_type": "threshold",
        "priority": 30,
        "condition": "batch.remaining_shelf_life < 90",
        "action": "flag_short_dated",
    },
    {
        "code": "BR-INV-003",
        "name": "Auto Replenishment Trigger",
        "category": "inventory",
        "rule_type": "threshold",
        "priority": 35,
        "condition": "inventory.qty < reorder_point",
        "action": "create_transfer_order",
    },
    {
        "code": "BR-PROMO-001",
        "name": "Promo Lift Application",
        "category": "promotion",
        "rule_type": "calculation",
        "priority": 20,
        "condition": "promotion.is_active = true",
        "action": "apply_lift_multiplier",
    },
    {
        "code": "BR-PROMO-002",
        "name": "Promo Hangover Adjustment",
        "category": "promotion",
        "rule_type": "calculation",
        "priority": 21,
        "condition": "promotion.ended_within_7_days",
        "action": "apply_hangover_multiplier",
    },
    {
        "code": "BR-CREDIT-001",
        "name": "Credit Hold Check",
        "category": "credit",
        "rule_type": "constraint",
        "priority": 5,
        "condition": "account.credit_balance > credit_limit",
        "action": "hold_order",
    },
    {
        "code": "BR-CREDIT-002",
        "name": "Payment Terms Validation",
        "category": "credit",
        "rule_type": "constraint",
        "priority": 10,
        "condition": "account.past_due > 60",
        "action": "require_prepayment",
    },
    {
        "code": "BR-PRICE-001",
        "name": "Trade Discount Application",
        "category": "pricing",
        "rule_type": "calculation",
        "priority": 15,
        "condition": "account.has_trade_agreement",
        "action": "apply_discount",
    },
    {
        "code": "BR-PRICE-002",
        "name": "Volume Tier Pricing",
        "category": "pricing",
        "rule_type": "calculation",
        "priority": 20,
        "condition": "order.qty >= volume_break",
        "action": "apply_tier_price",
    },
]
