-- ============================================================================
-- Prism Consumer Goods (PCG) - ERP Schema v0.78.0
-- ============================================================================
-- Target: PostgreSQL
-- Generated by: scripts/erp/ (Enterprise Data Generator)
--
-- Matches CSV output structure from `python -m scripts.erp`
-- Load data with: bash data/output/erp/load_postgres.sh
-- ============================================================================

-- Drop all tables (reverse dependency order) for clean reload
DROP TABLE IF EXISTS ar_receipts CASCADE;
DROP TABLE IF EXISTS ap_payments CASCADE;
DROP TABLE IF EXISTS invoice_variances CASCADE;
DROP TABLE IF EXISTS ar_invoice_lines CASCADE;
DROP TABLE IF EXISTS ar_invoices CASCADE;
DROP TABLE IF EXISTS ap_invoice_lines CASCADE;
DROP TABLE IF EXISTS ap_invoices CASCADE;
DROP TABLE IF EXISTS gl_journal CASCADE;
DROP TABLE IF EXISTS chart_of_accounts CASCADE;
DROP TABLE IF EXISTS disposition_logs CASCADE;
DROP TABLE IF EXISTS return_lines CASCADE;
DROP TABLE IF EXISTS returns CASCADE;
DROP TABLE IF EXISTS demand_forecasts CASCADE;
DROP TABLE IF EXISTS inventory CASCADE;
DROP TABLE IF EXISTS shipment_lines CASCADE;
DROP TABLE IF EXISTS shipments CASCADE;
DROP TABLE IF EXISTS order_lines CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS batch_ingredients CASCADE;
DROP TABLE IF EXISTS batches CASCADE;
DROP TABLE IF EXISTS work_orders CASCADE;
DROP TABLE IF EXISTS goods_receipt_lines CASCADE;
DROP TABLE IF EXISTS goods_receipts CASCADE;
DROP TABLE IF EXISTS purchase_order_lines CASCADE;
DROP TABLE IF EXISTS purchase_orders CASCADE;
DROP TABLE IF EXISTS supplier_ingredients CASCADE;
DROP TABLE IF EXISTS route_segments CASCADE;
DROP TABLE IF EXISTS production_lines CASCADE;
DROP TABLE IF EXISTS formula_ingredients CASCADE;
DROP TABLE IF EXISTS formulas CASCADE;
DROP TABLE IF EXISTS channels CASCADE;
DROP TABLE IF EXISTS retail_locations CASCADE;
DROP TABLE IF EXISTS distribution_centers CASCADE;
DROP TABLE IF EXISTS bulk_intermediates CASCADE;
DROP TABLE IF EXISTS skus CASCADE;
DROP TABLE IF EXISTS ingredients CASCADE;
DROP TABLE IF EXISTS plants CASCADE;
DROP TABLE IF EXISTS suppliers CASCADE;

-- ============================================================================
-- DOMAIN A: SOURCE (Procurement & Inbound)
-- ============================================================================

CREATE TABLE suppliers (
    id SERIAL PRIMARY KEY,
    supplier_code VARCHAR(30) UNIQUE NOT NULL,
    name VARCHAR(200) NOT NULL,
    city VARCHAR(100),
    country VARCHAR(100) NOT NULL,
    lat DECIMAL(10,6),
    lon DECIMAL(10,6),
    tier INTEGER NOT NULL DEFAULT 1,
    is_active BOOLEAN DEFAULT true
);

CREATE TABLE ingredients (
    id SERIAL PRIMARY KEY,
    ingredient_code VARCHAR(30) UNIQUE NOT NULL,
    name VARCHAR(200) NOT NULL,
    category VARCHAR(50) NOT NULL,
    subcategory VARCHAR(30),         -- base_material, active_ingredient, packaging
    bom_level INTEGER DEFAULT 2,
    weight_kg DECIMAL(12,4),
    cost_per_kg DECIMAL(12,4),
    unit_of_measure VARCHAR(20) NOT NULL DEFAULT 'kg',
    is_active BOOLEAN DEFAULT true
);

CREATE TABLE supplier_ingredients (
    id SERIAL PRIMARY KEY,
    supplier_id INTEGER NOT NULL REFERENCES suppliers(id),
    ingredient_id INTEGER NOT NULL REFERENCES ingredients(id),
    unit_cost DECIMAL(12,4) NOT NULL,
    lead_time_days INTEGER NOT NULL,
    min_order_qty DECIMAL(12,2) NOT NULL
);

CREATE TABLE purchase_orders (
    id SERIAL PRIMARY KEY,
    po_number VARCHAR(30) NOT NULL,
    supplier_id INTEGER REFERENCES suppliers(id),
    plant_id INTEGER,
    order_date INTEGER NOT NULL,
    status VARCHAR(20) DEFAULT 'open',
    transaction_sequence_id BIGINT NOT NULL
);

CREATE TABLE purchase_order_lines (
    po_id INTEGER NOT NULL REFERENCES purchase_orders(id),
    line_number INTEGER NOT NULL,
    ingredient_id INTEGER NOT NULL,
    quantity_kg DECIMAL(12,2) NOT NULL,
    unit_cost DECIMAL(10,4),
    status VARCHAR(20) DEFAULT 'open',
    PRIMARY KEY (po_id, line_number)
);

CREATE TABLE goods_receipts (
    id SERIAL PRIMARY KEY,
    gr_number VARCHAR(50) UNIQUE NOT NULL,
    shipment_id INTEGER,
    plant_id INTEGER,
    receipt_date INTEGER NOT NULL,
    status VARCHAR(20) DEFAULT 'received',
    transaction_sequence_id BIGINT NOT NULL
);

CREATE TABLE goods_receipt_lines (
    gr_id INTEGER NOT NULL REFERENCES goods_receipts(id),
    line_number INTEGER NOT NULL,
    ingredient_id INTEGER NOT NULL,
    quantity_kg DECIMAL(12,2) NOT NULL,
    PRIMARY KEY (gr_id, line_number)
);

-- ============================================================================
-- DOMAIN B: TRANSFORM (Manufacturing)
-- ============================================================================

CREATE TABLE plants (
    id SERIAL PRIMARY KEY,
    plant_code VARCHAR(20) UNIQUE NOT NULL,
    name VARCHAR(200) NOT NULL,
    city VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    lat DECIMAL(10,6),
    lon DECIMAL(10,6),
    capacity_tons_per_day DECIMAL(10,2),
    is_active BOOLEAN DEFAULT true
);

CREATE TABLE production_lines (
    id SERIAL PRIMARY KEY,
    line_code VARCHAR(30) UNIQUE NOT NULL,
    name VARCHAR(200) NOT NULL,
    plant_id INTEGER NOT NULL REFERENCES plants(id),
    line_type VARCHAR(50) NOT NULL,
    capacity_units_per_hour INTEGER NOT NULL,
    is_active BOOLEAN DEFAULT true
);

CREATE TABLE formulas (
    id SERIAL PRIMARY KEY,
    formula_code VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(200) NOT NULL,
    product_id INTEGER,
    bom_level INTEGER NOT NULL DEFAULT 0,   -- 0=SKU→BULK, 1=BULK→RM
    batch_size_kg DECIMAL(10,2) NOT NULL,
    yield_percent DECIMAL(5,2) DEFAULT 98.00,
    run_rate_cases_per_hour DECIMAL(10,2),
    changeover_time_hours DECIMAL(5,2)
);

CREATE TABLE formula_ingredients (
    formula_id INTEGER NOT NULL REFERENCES formulas(id),
    ingredient_id INTEGER NOT NULL,
    sequence INTEGER NOT NULL,
    quantity_kg DECIMAL(10,6) NOT NULL,
    PRIMARY KEY (formula_id, ingredient_id, sequence)
);

CREATE TABLE work_orders (
    id SERIAL PRIMARY KEY,
    wo_number VARCHAR(30) UNIQUE NOT NULL,
    plant_id INTEGER NOT NULL,
    formula_id INTEGER NOT NULL,
    planned_quantity_kg DECIMAL(12,2) NOT NULL,
    planned_start_date INTEGER NOT NULL,
    due_date INTEGER,
    status VARCHAR(20) DEFAULT 'planned',
    transaction_sequence_id BIGINT NOT NULL
);

CREATE TABLE batches (
    id SERIAL PRIMARY KEY,
    batch_number VARCHAR(30) UNIQUE NOT NULL,
    wo_id INTEGER,
    plant_id INTEGER REFERENCES plants(id),
    formula_id INTEGER REFERENCES formulas(id),
    product_id INTEGER,
    quantity_kg DECIMAL(12,2) NOT NULL,
    yield_percent DECIMAL(5,2),
    production_date INTEGER NOT NULL,
    status VARCHAR(20) DEFAULT 'pending',
    product_type VARCHAR(20),           -- finished_good or bulk_intermediate
    bom_level INTEGER DEFAULT 0,
    transaction_sequence_id BIGINT NOT NULL
);

CREATE TABLE batch_ingredients (
    id SERIAL PRIMARY KEY,
    batch_id INTEGER NOT NULL REFERENCES batches(id),
    ingredient_id INTEGER NOT NULL,
    quantity_kg DECIMAL(12,4) NOT NULL
);

-- ============================================================================
-- DOMAIN C: PRODUCT (SKU Master)
-- ============================================================================

CREATE TABLE bulk_intermediates (
    id SERIAL PRIMARY KEY,
    bulk_code VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(200) NOT NULL,
    category VARCHAR(50) NOT NULL,
    bom_level INTEGER NOT NULL DEFAULT 1,
    weight_kg DECIMAL(12,4),
    cost_per_kg DECIMAL(12,4),
    unit_of_measure VARCHAR(20) DEFAULT 'kg',
    is_active BOOLEAN DEFAULT true
);

CREATE TABLE skus (
    id SERIAL PRIMARY KEY,
    sku_code VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(300) NOT NULL,
    category VARCHAR(50) NOT NULL,
    brand VARCHAR(50),
    units_per_case INTEGER DEFAULT 12,
    weight_kg DECIMAL(10,2),
    cost_per_case DECIMAL(10,2),
    price_per_case DECIMAL(10,2),
    value_segment VARCHAR(30),
    is_active BOOLEAN DEFAULT true,
    supersedes_sku_id INTEGER REFERENCES skus(id)  -- friction: old-code alias chain
);

-- ============================================================================
-- DOMAIN D: ORDER (Demand Signal)
-- ============================================================================

CREATE TABLE channels (
    id SERIAL PRIMARY KEY,
    channel_code VARCHAR(20) UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    channel_type VARCHAR(30) NOT NULL,
    is_active BOOLEAN DEFAULT true
);

CREATE TABLE orders (
    id SERIAL PRIMARY KEY,
    order_number VARCHAR(50) UNIQUE NOT NULL,
    day INTEGER NOT NULL,
    source_id INTEGER,
    retail_location_id INTEGER,
    status VARCHAR(20) DEFAULT 'pending',
    total_cases INTEGER,
    transaction_sequence_id BIGINT NOT NULL
);

CREATE TABLE order_lines (
    order_id INTEGER NOT NULL REFERENCES orders(id),
    line_number INTEGER NOT NULL,
    sku_id INTEGER NOT NULL,
    quantity_cases DECIMAL(12,2) NOT NULL,
    unit_price DECIMAL(10,2),
    status VARCHAR(20) DEFAULT 'open',
    PRIMARY KEY (order_id, line_number)
);

-- ============================================================================
-- DOMAIN E: FULFILL (Outbound)
-- ============================================================================

CREATE TABLE distribution_centers (
    id SERIAL PRIMARY KEY,
    dc_code VARCHAR(30) UNIQUE NOT NULL,
    name VARCHAR(200) NOT NULL,
    city VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    lat DECIMAL(10,6),
    lon DECIMAL(10,6),
    type VARCHAR(30) NOT NULL,
    is_active BOOLEAN DEFAULT true
);

CREATE TABLE retail_locations (
    id SERIAL PRIMARY KEY,
    location_code VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(200) NOT NULL,
    city VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    lat DECIMAL(10,6),
    lon DECIMAL(10,6),
    store_format VARCHAR(30),
    channel VARCHAR(30),
    is_active BOOLEAN DEFAULT true
);

CREATE TABLE shipments (
    id SERIAL PRIMARY KEY,
    shipment_number VARCHAR(50) UNIQUE NOT NULL,
    ship_date INTEGER NOT NULL,
    arrival_date INTEGER,
    origin_id INTEGER,
    destination_id INTEGER,
    status VARCHAR(20) DEFAULT 'planned',
    route_type VARCHAR(30),
    freight_cost DECIMAL(12,2),
    total_weight_kg DECIMAL(12,2),
    transaction_sequence_id BIGINT NOT NULL
);

CREATE TABLE shipment_lines (
    shipment_id INTEGER NOT NULL REFERENCES shipments(id),
    line_number INTEGER NOT NULL,
    sku_id INTEGER NOT NULL,
    quantity_cases DECIMAL(12,2) NOT NULL,
    weight_kg DECIMAL(10,2),
    PRIMARY KEY (shipment_id, line_number)
);

CREATE TABLE inventory (
    id SERIAL PRIMARY KEY,
    day INTEGER NOT NULL,
    location_type VARCHAR(20),
    location_id INTEGER,
    sku_id INTEGER NOT NULL,
    quantity_cases DECIMAL(12,2) NOT NULL DEFAULT 0
);

-- ============================================================================
-- DOMAIN E2: LOGISTICS (Transport Network)
-- ============================================================================

CREATE TABLE route_segments (
    id SERIAL PRIMARY KEY,
    segment_code VARCHAR(50) UNIQUE NOT NULL,
    origin_type VARCHAR(20) NOT NULL,
    origin_id INTEGER NOT NULL,
    destination_type VARCHAR(20) NOT NULL,
    destination_id INTEGER NOT NULL,
    transport_mode VARCHAR(30) NOT NULL,
    distance_km DECIMAL(10,2),
    transit_time_hours DECIMAL(8,2)
);

-- ============================================================================
-- DOMAIN F: PLAN (Demand & Supply Planning)
-- ============================================================================

CREATE TABLE demand_forecasts (
    id SERIAL PRIMARY KEY,
    forecast_version VARCHAR(30) NOT NULL,
    sku_id INTEGER NOT NULL,
    location_type VARCHAR(20) NOT NULL,
    forecast_date INTEGER NOT NULL,
    forecast_quantity_cases DECIMAL(12,2) NOT NULL,
    forecast_type VARCHAR(30) NOT NULL
);

-- ============================================================================
-- DOMAIN G: RETURN (Regenerate)
-- ============================================================================

CREATE TABLE returns (
    id SERIAL PRIMARY KEY,
    return_number VARCHAR(30) UNIQUE NOT NULL,
    return_date INTEGER NOT NULL,
    source_id INTEGER NOT NULL,
    dc_id INTEGER NOT NULL,
    status VARCHAR(20) DEFAULT 'received',
    transaction_sequence_id BIGINT NOT NULL
);

CREATE TABLE return_lines (
    return_id INTEGER NOT NULL REFERENCES returns(id),
    line_number INTEGER NOT NULL,
    sku_id INTEGER NOT NULL,
    quantity_cases DECIMAL(12,2) NOT NULL,
    condition VARCHAR(20) NOT NULL,
    PRIMARY KEY (return_id, line_number)
);

CREATE TABLE disposition_logs (
    return_id INTEGER NOT NULL REFERENCES returns(id),
    return_line_number INTEGER NOT NULL,
    disposition VARCHAR(20) NOT NULL,
    quantity_cases DECIMAL(12,2) NOT NULL
);

-- ============================================================================
-- DOMAIN H: FINANCE (New in v0.73.0)
-- ============================================================================

CREATE TABLE chart_of_accounts (
    id SERIAL PRIMARY KEY,
    account_code VARCHAR(10) UNIQUE NOT NULL,
    account_name VARCHAR(200) NOT NULL,
    account_type VARCHAR(30) NOT NULL,     -- asset, liability, revenue, expense
    is_active BOOLEAN DEFAULT true
);

CREATE TABLE gl_journal (
    id SERIAL PRIMARY KEY,
    transaction_sequence_id BIGINT NOT NULL,
    entry_date INTEGER NOT NULL,
    posting_date INTEGER NOT NULL,
    account_code VARCHAR(10) NOT NULL,
    debit_amount DECIMAL(14,4) DEFAULT 0,
    credit_amount DECIMAL(14,4) DEFAULT 0,
    reference_type VARCHAR(30) NOT NULL,
    reference_id VARCHAR(50),
    node_id VARCHAR(50),
    product_id VARCHAR(50),
    description TEXT,
    is_reversal BOOLEAN DEFAULT false
);

CREATE TABLE ap_invoices (
    id SERIAL PRIMARY KEY,
    transaction_sequence_id BIGINT NOT NULL,
    invoice_number VARCHAR(30) UNIQUE NOT NULL,
    supplier_id INTEGER REFERENCES suppliers(id),
    gr_id INTEGER REFERENCES goods_receipts(id),
    invoice_date INTEGER NOT NULL,
    due_date INTEGER NOT NULL,
    total_amount DECIMAL(14,4) NOT NULL,
    currency VARCHAR(3) DEFAULT 'USD',
    status VARCHAR(20) DEFAULT 'open'
);

CREATE TABLE ap_invoice_lines (
    invoice_id INTEGER NOT NULL REFERENCES ap_invoices(id),
    line_number INTEGER NOT NULL,
    ingredient_id INTEGER NOT NULL,
    quantity_kg DECIMAL(12,4) NOT NULL,
    unit_cost DECIMAL(10,4) NOT NULL,
    line_amount DECIMAL(14,4) NOT NULL,
    PRIMARY KEY (invoice_id, line_number)
);

CREATE TABLE ar_invoices (
    id SERIAL PRIMARY KEY,
    transaction_sequence_id BIGINT NOT NULL,
    invoice_number VARCHAR(30) UNIQUE NOT NULL,
    customer_location_id INTEGER,
    shipment_id INTEGER REFERENCES shipments(id),
    invoice_date INTEGER NOT NULL,
    due_date INTEGER NOT NULL,
    total_amount DECIMAL(14,4) NOT NULL,
    currency VARCHAR(3) DEFAULT 'USD',
    channel VARCHAR(30),
    status VARCHAR(20) DEFAULT 'open'
);

CREATE TABLE ar_invoice_lines (
    invoice_id INTEGER NOT NULL REFERENCES ar_invoices(id),
    line_number INTEGER NOT NULL,
    sku_id INTEGER NOT NULL,
    quantity_cases DECIMAL(12,2) NOT NULL,
    unit_price DECIMAL(10,4) NOT NULL,
    line_amount DECIMAL(14,4) NOT NULL,
    PRIMARY KEY (invoice_id, line_number)
);

-- ============================================================================
-- DOMAIN H2: FRICTION (New in v0.78.0 — controlled data quality noise)
-- ============================================================================

CREATE TABLE invoice_variances (
    id SERIAL PRIMARY KEY,
    invoice_id INTEGER NOT NULL REFERENCES ap_invoices(id),
    line_number INTEGER NOT NULL,
    variance_type VARCHAR(10) NOT NULL,      -- 'price' or 'qty'
    expected_value DECIMAL(14,4) NOT NULL,
    actual_value DECIMAL(14,4) NOT NULL,
    variance_amount DECIMAL(14,4) NOT NULL,
    resolution_status VARCHAR(20) DEFAULT 'open'
);

CREATE TABLE ap_payments (
    id SERIAL PRIMARY KEY,
    transaction_sequence_id BIGINT NOT NULL,
    invoice_id INTEGER NOT NULL REFERENCES ap_invoices(id),
    payment_date INTEGER NOT NULL,
    amount DECIMAL(14,4) NOT NULL,
    discount_amount DECIMAL(14,4) DEFAULT 0,
    net_amount DECIMAL(14,4) NOT NULL,
    payment_method VARCHAR(20) DEFAULT 'EFT',
    status VARCHAR(20) DEFAULT 'completed'
);

CREATE TABLE ar_receipts (
    id SERIAL PRIMARY KEY,
    transaction_sequence_id BIGINT NOT NULL,
    invoice_id INTEGER NOT NULL REFERENCES ar_invoices(id),
    receipt_date INTEGER NOT NULL,
    amount DECIMAL(14,4) NOT NULL,
    status VARCHAR(20) DEFAULT 'completed'
);

-- ============================================================================
-- Indexes
-- ============================================================================

CREATE INDEX idx_orders_day ON orders(day);
CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_shipments_ship_date ON shipments(ship_date);
CREATE INDEX idx_shipments_route_type ON shipments(route_type);
CREATE INDEX idx_inventory_day ON inventory(day);
CREATE INDEX idx_inventory_location ON inventory(location_id);
CREATE INDEX idx_batches_production_date ON batches(production_date);
CREATE INDEX idx_gl_journal_entry_date ON gl_journal(entry_date);
CREATE INDEX idx_gl_journal_account ON gl_journal(account_code);
CREATE INDEX idx_gl_journal_seq ON gl_journal(transaction_sequence_id);
CREATE INDEX idx_gl_journal_reference ON gl_journal(reference_id);
CREATE INDEX idx_ap_invoices_date ON ap_invoices(invoice_date);
CREATE INDEX idx_ar_invoices_date ON ar_invoices(invoice_date);
CREATE INDEX idx_ar_invoices_channel ON ar_invoices(channel);
CREATE INDEX idx_invoice_variances_invoice ON invoice_variances(invoice_id);
CREATE INDEX idx_ap_payments_invoice ON ap_payments(invoice_id);
CREATE INDEX idx_ap_payments_date ON ap_payments(payment_date);
CREATE INDEX idx_ar_receipts_invoice ON ar_receipts(invoice_id);
CREATE INDEX idx_ar_receipts_date ON ar_receipts(receipt_date);
